package de.thi.services;

import org.camunda.bpm.engine.delegate.DelegateExecution;
import org.camunda.bpm.engine.delegate.JavaDelegate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class OutputUser implements JavaDelegate {
    private static final Logger LOG = LoggerFactory.getLogger(OutputUser.class);

    @Override
    public void execute(DelegateExecution execution) throws Exception {
        User user = (User) execution.getVariable("user");
        Integer loopCounter = (Integer) execution.getVariable("loopCounter");
        // Log Userdate (mostly for debugging)
        logUser(user, loopCounter);

        // Write User attributes to  Process variables
        // not outsources to a method, because execution is accessed
        // (Generated by Copilot)
        execution.setVariableLocal("vorname", user.getVorname());
        execution.setVariableLocal("nachname", user.getNachname());
        execution.setVariableLocal("alter", user.getAlter());
        execution.setVariableLocal("mitgliedschaft", user.getMitgliedschaft());
        execution.setVariableLocal("mitgliedschaftsdauer", user.getMitgliedschaftsdauer());
        execution.setVariableLocal("artDerAktivitaet", user.getArtDerAktivitaet());
        execution.setVariableLocal("ehrenmitglied", user.isEhrenmitglied());
        execution.setVariableLocal("beitragsanpassungGestartet", user.isBeitragsanpassungGestartet());
        execution.setVariableLocal("beitrag", user.getBeitrag());

    }


    public void logUser(User user, Integer loopCounter){
        LOG.info("######################");
        LOG.info("Trying to output user of instance " + loopCounter);

        LOG.info("Vorame: " + user.getVorname());
        LOG.info("Nachname: " + user.getNachname());
        LOG.info("Alter: " + user.getAlter());
        LOG.info("Mitgliedschaft: " + user.getMitgliedschaft());
        LOG.info("Mitgliedschaftsdauer: " + user.getMitgliedschaftsdauer());
        LOG.info("Art der Aktivität: " + user.getArtDerAktivitaet());
        LOG.info("Ehrenmitglied: " + user.isEhrenmitglied());
        LOG.info("Beitragsanpassung gestartet: " + user.isBeitragsanpassungGestartet());

        LOG.info("######################");
    }
}
