package de.thi.services;

import camundajar.impl.com.google.gson.Gson;
import org.camunda.bpm.engine.delegate.DelegateExecution;
import org.camunda.bpm.engine.delegate.JavaDelegate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


import java.util.LinkedList;
import java.util.List;

public class ReadMember implements JavaDelegate {

    // Get Logger
    private static final Logger LOG = LoggerFactory.getLogger(ReadMember.class);

    @Override
    public void execute(DelegateExecution execution) throws Exception {
        LOG.info("ReadMember called");

        // Generated by ChatGPT
       String userString = """
                              
                [
                  {
                    "vorname": "Max",
                    "nachname": "Mustermann",
                    "alter": 30,
                    "mitgliedschaft": "Premium",
                    "mitgliedschaftsdauer": 2,
                    "artDerAktivitaet": "Freizeit",
                    "ehrenmitglied": false
                  },
                  {
                    "vorname": "Anna",
                    "nachname": "Schmidt",
                    "alter": 25,
                    "mitgliedschaft": "Standard",
                    "mitgliedschaftsdauer": 1,
                    "artDerAktivitaet": "Wettkampf",
                    "ehrenmitglied": true
                  },
                  {
                    "vorname": "Michael",
                    "nachname": "Müller",
                    "alter": 40,
                    "mitgliedschaft": "Premium",
                    "mitgliedschaftsdauer": 3,
                    "artDerAktivitaet": "Freizeit",
                    "ehrenmitglied": false
                  },
                  {
                    "vorname": "Julia",
                    "nachname": "Schneider",
                    "alter": 35,
                    "mitgliedschaft": "Standard",
                    "mitgliedschaftsdauer": 2,
                    "artDerAktivitaet": "Wettkampf",
                    "ehrenmitglied": false
                  },
                  {
                    "vorname": "Thomas",
                    "nachname": "Fischer",
                    "alter": 28,
                    "mitgliedschaft": "Premium",
                    "mitgliedschaftsdauer": 1,
                    "artDerAktivitaet": "Freizeit",
                    "ehrenmitglied": true
                  }
                ]
                              
               """;

        Gson gson = new Gson();
        User[] userArray = gson.fromJson(userString, User[].class);

        execution.setVariable("userArray",userArray);
    }
}
